on:
  push:
    branches:
      - master
    tags:
      - '*'
name: Build Docker Image
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kylemcc/dns-gen
        add_git_labels: true
    - name: Send Slack Notification
      uses: kylemcc/actions/slack-webhook@master
      if: always()
      env:
        SLACK_MESSAGE: '$GITHUB_REPOSITORY: Build ${{ job.status }}'
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
